version: '3.8'

services:
  backend-test:
    build: .
    environment:
      - DB_HOST=db-test
      - DB_NAME=testdb
      - DB_USER=user
      - DB_PASSWORD=password
      - FLASK_ENV=testing
      - PYTHONPATH=/app  # <--- ДОБАВЬТЕ ЭТУ СТРОКУ
    command: ["pytest"]
    depends_on:
      - db-test

  db-test:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGUSER=user
      - POSTGRES_PASSWORD=password