name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t dreamy3/docker-notes-app:latest .
          docker push dreamy3/docker-notes-app:latest